ALTER TABLE services ADD COLUMN IF NOT EXISTS port INTEGER DEFAULT 0;
ALTER TABLE services ADD COLUMN IF NOT EXISTS command JSONB DEFAULT '[]'::jsonb;
ALTER TABLE services ADD COLUMN IF NOT EXISTS args JSONB DEFAULT '[]'::jsonb;